### ISSUE TITLE
missing sub_492810() in Re Utility functions

### ISSUE THREAD

**Issue by Olganix** [OpenSWE1R/swe1r-re#31]
this function is used here (allready in the RE with matrix operations) : 
```
//----- (00493130) --------------------------------------------------------
// a1 = output matrix (12 floats)
// a2 = ?
float* __cdecl sub_493130(float* a1, float* a2) {
  float tmp[12];
  sub_492810(tmp, a2);
  return sub_492D50(a1, tmp);
}
```
sub_492D50() is a function witch mutiply 2 Matrix4x3 (Transposed ?).
So tmp is a Matrix and a2 help to making it into sub_492810().

**Comment by JayFoxRox** [comment]
Again, please always add the game version (which is the patched US version in this case).

I also don't understand what this issue is about:
Yes `sub_492810` does not seem to be documented yet.
And yes, `tmp` is obviously a matrix.
Yes, `sub_492810` somehow takes `a2` as input and has `tmp` as output.

Unless you can tell us what exactly `sub_492810` does, and in turn what `sub_493130` does, this issue is pointless. There's also thousands of undocumented functions.
And this function is not particularily interesting.

It's also easy to tell that something is missing, but with so much context it's also easy to tell what the in- and outputs are. Often the actions can also be inferred. However, the question is: What does it do *exactly* and how does it work internally?

Example: Looking at `sub_492810` it's also clearly some sort of matrix function which has to do with rotation (as it uses `sub_48C950` internally). But this information is useless until it's properly documented.

**Comment by JayFoxRox** [comment]
Closed due to lack of documentation. We don't keep issues for missing functions.

A new issue could be opened with appropriate title if the action of the function is found.
